common: &common_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *common_settings
  database: cables_development

test:
  <<: *common_settings
  database: cables_test

production:
  <<: *common_settings
  database: cables_production
